"use strict";

window.hamzaStoneCatalog = [
  { name: "Beige Taza Bouchardé", image: "beige-taza-boucharde-1.jpg", url: "beige-taza-boucharde", color: "beige", finish: "Bouchardé", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Poli", image: "beige-taza-poli-1.jpg", url: "beige-taza-poli", color: "beige", finish: "Poli", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Brut", image: "beige-taza-brut-1.jpg", url: "beige-taza-brut", color: "beige", finish: "Brut", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Vieilli", image: "beige-taza-vieilli-1.jpg", url: "beige-taza-vieilli", color: "beige", finish: "Vieilli", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Strié", image: "beige-taza-strie-1.jpg", url: "beige-taza-strie", color: "beige", finish: "Strié", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Veinage", image: "beige-taza-veinage-1.jpg", url: "beige-taza-veinage", color: "beige", finish: "Veinage", group: "Pierre naturelle & Taza" },
  { name: "Beige Taza Sablé", image: "beige-taza-sable-1.jpg", url: "beige-taza-sable", color: "beige", finish: "Sablé", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Bouchardé", image: "gris-taza-boucharde-1.jpg", url: "gris-taza-boucharde", color: "gris", finish: "Bouchardé", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Poli", image: "gris-taza-poli-1.jpg", url: "gris-taza-poli", color: "gris", finish: "Poli", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Brut", image: "gris-taza-brut-1.jpg", url: "gris-taza-brut", color: "gris", finish: "Brut", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Vieilli", image: "gris-taza-vieilli-1.jpg", url: "gris-taza-vieilli", color: "gris", finish: "Vieilli", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Veinage", image: "gris-taza-veinage-1.jpg", url: "gris-taza-veinage", color: "gris", finish: "Veinage", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Strié", image: "gris-taza-strie-1.jpg", url: "gris-taza-strie", color: "gris", finish: "Strié", group: "Pierre naturelle & Taza" },
  { name: "Gris Taza Sablé", image: "gris-taza-sable-1.jpg", url: "gris-taza-sable", color: "gris", finish: "Sablé", group: "Pierre naturelle & Taza" },
  { name: "Pierre Volcanique", image: "pierre-volcanique-1.jpg", url: "pierre-volcanique", color: "sombre", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Pierre Volcanique Noire", image: "pierre-volcanique-noire.jpg", url: "pierre-volcanique-noire", color: "sombre", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Volubilis", image: "travertin-volubilis.jpg", url: "volubilis", color: "beige", finish: "Naturelle", group: "Pierre naturelle & Taza" },
  { name: "Pierre Naturelle", image: "realisation-exterieur.jpg", url: "pierre-naturelle", color: "varié", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Éclaté Gris Taza", image: "eclate-gris-taza-1.jpg", url: "eclate-gris-taza", color: "gris", finish: "Éclaté", group: "Pierre naturelle & Taza" },
  { name: "Éclaté Volubilis", image: "eclate-volubilis-1.jpg", url: "eclate-volubilis", color: "beige", finish: "Éclaté", group: "Pierre naturelle & Taza" },
  { name: "Éclaté Rouge Rosé", image: "eclate-rouge-rose-1.jpg", url: "eclate-rouge-rose", color: "rouge", finish: "Éclaté", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Beige Éclatée", image: "eclate-beige.jpg", url: "pierre-taza-beige-eclatee", color: "beige", finish: "Éclatée", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Beige 30/10 cm", image: "pierre-taza-beige-30-10-1.jpg", url: "pierre-taza-beige-30-10", color: "beige", finish: "Format 30/10 cm", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Grise 30/10 cm", image: "pierre-taza-grise.jpg", url: "pierre-taza-grise-30-10", color: "gris", finish: "Format 30/10 cm", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Grise (Polie, 20/20 cm)", image: "pierre-taza-grise-polie-20-20-1.jpg", url: "pierre-taza-grise-polie-20-20", color: "gris", finish: "Polie · 20/20 cm", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Beige (Bouchardée, 30/30 cm)", image: "pierre-taza-beige-bouchardee-30-30-1.jpg", url: "pierre-taza-beige-bouchardee-30-30", color: "beige", finish: "Bouchardée · 30/30 cm", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Beige (Polie, 30/60 cm)", image: "pierre-taza-beige-polie-30-60-1.jpg", url: "pierre-taza-beige-polie-30-60", color: "beige", finish: "Polie · 30/60 cm", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Brut", image: "pierre-taza-brut-1.jpg", url: "pierre-taza-brut", color: "varié", finish: "Brut", group: "Pierre naturelle & Taza" },
  { name: "Pierre Taza Beige Strié", image: "pierre-taza-beige-strie-1.jpg", url: "pierre-taza-beige-strie", color: "beige", finish: "Strié", group: "Pierre naturelle & Taza" },
  { name: "Pierre Naturelle Beige Carthabon", image: "pierre-naturelle-beige-carthabon-1.jpg", url: "pierre-naturelle-beige-carthabon", color: "beige", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Zola Vieille", image: "zola-vieille-1.jpg", url: "zola-vieille", color: "varié", finish: "Naturelle", group: "Marbre local" },
  { name: "Bir Jdid", image: "bir-jdid-1.jpg", url: "bir-jdid", color: "varié", finish: "Naturelle", group: "Marbre local" },
  { name: "Éclaté Noir Khénifra", image: "eclate-noir-khenifra-1.jpg", url: "eclate-noir-khenifra", color: "sombre", finish: "Éclaté", group: "Pierre naturelle" },
  { name: "Éclaté Noir Azilal", image: "eclate-noir-azilal-1.jpg", url: "eclate-noir-azilal", color: "sombre", finish: "Éclaté", group: "Pierre naturelle" },
  { name: "Noir Khénifra", image: "noir-khenifra-1.jpg", url: "noir-khenifra", color: "sombre", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Gris Khénifra", image: "granit-gris-khenifra.jpg", url: "gris-khenifra", color: "gris", finish: "Naturelle", group: "Granit" },
  { name: "Gris Tiflet", image: "gris-tiflet-1.jpg", url: "gris-tiflet", color: "gris", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Gris Benslimane", image: "gris-benslimane-1.jpg", url: "gris-benslimane", color: "gris", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Noir Azilal", image: "noir-azilal.jpg", url: "noir-azilal", color: "sombre", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Jaune Béjaâd", image: "jaune-bejaad-1.jpg", url: "jaune-bejaad", color: "jaune", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Rouge Agadir", image: "rouge-agadir-1.jpg", url: "rouge-agadir", color: "rouge", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Pierres Ardoise Vert Forêt", image: "pierres-ardoise-vert-foret-1.jpg", url: "pierres-ardoise-vert-foret", color: "vert", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise Gris Béni Khirane", image: "ardoise-gris-beni-khirane-1.jpg", url: "ardoise-gris-beni-khirane", color: "gris", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise Violet Foncé", image: "ardoise-violet-fonce-1.jpg", url: "ardoise-violet-fonce", color: "violet", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise", image: "ardoise-1.jpg", url: "ardoise", color: "varié", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise Noire", image: "ardoise-noire-1.jpg", url: "ardoise-noire", color: "sombre", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise Verte", image: "ardoise-verte-1.jpg", url: "ardoise-verte", color: "vert", finish: "Naturelle", group: "Ardoise" },
  { name: "Plinta", image: "plinta-1.jpg", url: "plinta", color: "varié", finish: "Naturelle", group: "Pierre naturelle" },
  { name: "Ardoise Noir Volcan", image: "ardoise-noir-volcan-1.jpg", url: "ardoise-noir-volcan", color: "sombre", finish: "Naturelle", group: "Ardoise" },
  { name: "Ardoise Bronzée", image: "ardoise-bronzee-1.jpg", url: "ardoise-bronzee", color: "bronzé", finish: "Naturelle", group: "Ardoise" }
];
